# Generated by Django 4.1.7 on 2023-02-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_mainpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopage',
            name='video_1080',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='1080'),
        ),
        migrations.AddField(
            model_name='videopage',
            name='video_144',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='144'),
        ),
        migrations.AddField(
            model_name='videopage',
            name='video_240',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='240'),
        ),
        migrations.AddField(
            model_name='videopage',
            name='video_360',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='360'),
        ),
        migrations.AddField(
            model_name='videopage',
            name='video_480',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='480'),
        ),
        migrations.AddField(
            model_name='videopage',
            name='video_720',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='720'),
        ),
    ]
