# Generated by Django 4.1.7 on 2023-02-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_videopage_video_1080_videopage_video_144_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videopage',
            name='original_size_height',
        ),
        migrations.RemoveField(
            model_name='videopage',
            name='original_size_width',
        ),
        migrations.RemoveField(
            model_name='videopage',
            name='video_144',
        ),
        migrations.RemoveField(
            model_name='videopage',
            name='video_240',
        ),
        migrations.AddField(
            model_name='videopage',
            name='original_height',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videopage',
            name='original_width',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videopage',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='videopage',
            name='duration',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videopage',
            name='image',
            field=models.ImageField(blank=True, default=0, upload_to='', verbose_name='Превью'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videopage',
            name='video_1080',
            field=models.FileField(blank=True, default=0, upload_to='', verbose_name='1080'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videopage',
            name='video_360',
            field=models.FileField(blank=True, default=0, upload_to='', verbose_name='360'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videopage',
            name='video_480',
            field=models.FileField(blank=True, default=0, upload_to='', verbose_name='480'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videopage',
            name='video_720',
            field=models.FileField(blank=True, default=0, upload_to='', verbose_name='720'),
            preserve_default=False,
        ),
    ]
