# Generated by Django 4.1.7 on 2023-02-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_remove_videopage_original_size_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopage',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
