# Generated by Django 4.1.7 on 2023-02-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_alter_videopage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopage',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videopage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='videopage',
            name='original_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videopage',
            name='original_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videopage',
            name='video_1080',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='1080'),
        ),
        migrations.AlterField(
            model_name='videopage',
            name='video_360',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='360'),
        ),
        migrations.AlterField(
            model_name='videopage',
            name='video_480',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='480'),
        ),
        migrations.AlterField(
            model_name='videopage',
            name='video_720',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='720'),
        ),
    ]
