# Generated by Django 4.1.7 on 2023-03-06 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_alter_videopage_duration_alter_videopage_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videopage',
            old_name='original_video',
            new_name='video_original',
        ),
    ]
